server:
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: local
    import:
      - application-core-local.yml
      - application-kafka-local.yml
  task:
    scheduling:
      pool:
        size: 5
  lifecycle:
    timeout-per-shutdown-phase: 30s


#aws:
#  credential:
#    enabled: false
#    accessKey: ${AWS_ACCESS_KEY}
#    secretKey: ${AWS_SECRET_KEY}
#  region: ${AWS_REGION}
#  s3:
#    bucket: ${BUCKET}
#    default-folder: ${DEFAULT_FOLDER}

#web-client:
#  hk:
#    client-id: "test"
#    url:
#      order: "http://localhost:8080/orders"
#      return-order: "http://localhost:8080/returns"
#  tw:
#    client-id: "test"
#    url:
#      order: "http://localhost:8080/orders"
#      return-order: "http://localhost:8080/returns"
#  us:
#    client-id: "test"
#    url:
#      order: "http://localhost:8080/orders"
#      return-order: "http://localhost:8080/returns"
#  kr:
#    client-id: "test"
#    url:
#      order: "https://saturn-gateway-api.dev.kr.riman.com/order/v1/public/global/sales-order"
#      return-order: "https://saturn-gateway-api.dev.kr.riman.com/order/v1/public/global/return-order"
##      order: "http://localhost:8080/orders"
##      return-order: "http://localhost:8080/returns"

logging:
  file:
    path: /app/logs
  level:
    biz.riman: debug
    org.hibernate.orm.jdbc.bind: debug
