server:
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: local
    import:
      - application-core-local.yml
      - application-kafka-local.yml
  task:
    scheduling:
      pool:
        size: 5
  lifecycle:
    timeout-per-shutdown-phase: 30s


#aws:
#  credential:
#    enabled: false
#    accessKey: ${AWS_ACCESS_KEY}
#    secretKey: ${AWS_SECRET_KEY}
#  region: ${AWS_REGION}
#  s3:
#    bucket: ${BUCKET}
#    default-folder: ${DEFAULT_FOLDER}

web-client:
  hk:
    client-id: "test"
    url:
      order: "http://localhost:7711/local/order"
    api-key: "test"
  tw:
    client-id: "test"
    url:
      order: "http://localhost:7711/local/order"
    api-key: "test"
  us:
    client-id: "test"
    url:
      order: "http://localhost:7711/local/order"
    api-key: "test"
  kr:
    client-id: "test"
    url:
      order: "http://localhost:7711/local/order"
    api-key: "test"

logging:
  file:
    path: /app/logs
  level:
    org.hibernate.orm.jdbc.bind: debug
